[package]
name = "test_sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.28.0", features = ["signal"] }
libc = "0.2.153"

[build-dependencies]
bindgen = "0.69.4"

